version: 1.4.0
pipeline_os: windows
#update_changelog_on_release: true
create_github_release: true
create_pr_release_to_master: true

env:
  - GITHUB_ACCESS_TOKEN_ID: github_access_token_acsbuildguy
  - JENKINS_NODE_WIN: DynamoWinBuild

code_analysis:
  sonarqube:
    source_encoding: UTF-8
    src: .
    coverage_reports:
      - coverage.info

build:
  -
    scripts:
      - dotnet msbuild DynamoPythonNet3.sln -p:Configuration=Release -restore
      
ci_test:
  tests:
    -
      scripts:
        - dotnet test

deployment:
  -
    type: sign
    files_to_sign:
      - package_output/DSPythonNet3/**/DSPythonNet3*.dll
      - package_output/DSPythonNet3/**/Python.*.dll
  -
    type: customized
    scripts:
      - "pwsh.exe -ExecutionPolicy ByPass -Command Compress-Archive -Path package_output/DSPythonNet3 -DestinationPath DSPythonNet3.zip"
  -
    type: artifacts
    publish_to_jenkins: true
    publish_to_artifactory: false
    allow_branches: ".*"
    outputs:
      - DSPythonNet3.zip
